Repository gdsc-upt/git-starter, pull requests merged in 2023-11, with the labels that each got.

#40 pls
  Stefoni.Mircea/Ioana Roscata fotbalista.txt
  Stefoni.Mircea/Stefoni.Mircea.txt
Labels: bug, documentation, enhancement, good first issue, question, wontfix

#56 updated Best footballer.txt
  Best footballer.txt
  Manolache-Alex/Manolache-Alex.txt
Labels: enhancement

#69 pls
  Stefoni.Mircea/NU INTRA PE LINK.txt
Labels: bug, enhancement, good first issue

#72 ceva tare rau
  MoreRandomFiles.txt
Labels: documentation

#78 important changes
  👺
Labels: help wanted

#90 Poza adecvata pentru aceasta seara!
  Stefoni.Mircea/poza adecvata.png
Labels: enhancement
